### ISSUE TITLE
Create definition for application spec

### ISSUE THREAD

**Issue by wolf31o2** [demeter-run/fabric#1]
This covers the "application spec" in all of its forms.

- [ ] Repository information
  - [ ] Type (github/gitlab)
  - [ ] Owner / Repo
  - [ ] Branch

- [ ] Build / Deploy information
  - [ ] Command / Target path / root path / Development Command
  - [ ] Commit Ref
  - [ ] Environment variables

Logic splits:
- API definition
- Build definition
- Runtime definition
- Kubernetes Operator CRD

**Comment by scarmuega** [comment]
for long term, discuss how to enable taints / affinity by region / provider
